AWSTemplateFormatVersion: "2010-09-09"
Description: A module wrapping an Public SecurityGroup.

Parameters:
  VpcId:
    Type: String
  AllowedIp:
    Type: String

Resources:
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Public EC2 Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedIp
          
Outputs:
  SecurityGroupId:
    Value: !Ref PublicSecurityGroup


