AWSTemplateFormatVersion: '2010-09-09'
Description: VPC module
Parameters:
  CidrBlock:
    Type: String
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
Outputs:
  VpcId:
    Value: !Ref VPC